include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build-wheels
  - build-image
  - publish

build wheels:
  stage: build-wheels
  extends: .baremetal-runner-clariden-gh200
  variables:
    SLURM_TIMELIMT: '05:00:00'
  script:
    - podman build -f ci/Dockerfile-wheels -t my_image:latest
    - podman run --rm -it -v $PWD:/shared_with_host my_image:latest bash -c 'cp /workspace/wheels/*.whl /shared_with_host/'
  artifacts:
    paths:
      - *.whl

build image:
  stage: build-image
  extends: .container-builder-cscs-gh200
  variables:
    DOCKERFILE: ci/Dockerfile
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/my_final_build:$CI_COMMIT_SHA

publish wheel:
  stage: publish
  extends: .container-runner-lightweight-zen2
  rules:
    - if: $CI_COMMIT_REF == "main"
      when: on_success
  image: curl:latest
  script:
    - |
      curl -L \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer <YOUR-TOKEN>" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      -H "Content-Type: application/octet-stream" \
      "https://uploads.github.com/repos/swiss-ai/gh200-wheels/releases/RELEASE_ID/assets?name=example.zip" \
      --data-binary "@example.zip"
