include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build-base
  - build-wheels
  - build-image
  - test-image
  - publish

build base image:
  stage: build-base
  extends: .container-builder-cscs-gh200
  variables:
    DOCKERFILE: ci/Dockerfile-base
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base_image:$CI_COMMIT_SHA

build flash-attn:
  stage: build-wheels
  extends: .container-runner-clariden-gh200
  image: $PERSIST_IMAGE_NAME
  variables:
    SLURM_TIMELIMT: '03:00:00'
  script:
    - |
      git clone https://github.com/flashinfer-ai/flashinfer.git ;\
      cd flashinfer ;\
      git checkout 50319b2e59e94e4e4b6f175e11184a677e0053b2 ;\
      git submodule update --init --recursive ;\
      MAX_JOBS=32 python3 -m flashinfer.aot 2>&1 | tee ./build_aot.log ;\
      python3 -m build --wheel --no-isolation --outdir=${WHL_DIR} 2>&1 | tee ./build.log
    - |
      cd flash-attention ;\
      git checkout 1ceaa984b2f348caea18b39a98458d33b4ea7a09 ;\
      git submodule update --init --recursive ;\
      MAX_JOBS=4 python3 setup.py bdist_wheel --dist-dir=${WHL_DIR} 2>&1 | tee ../build_fa2.log ;\
      cd hopper ;\
      MAX_JOBS=16 python3 setup.py bdist_wheel --dist-dir=${WHL_DIR} 2>&1 | tee ../build_fa3.log
  artifacts:
    paths:
      - ./*.whl

build torch_memory_saver:
  stage: build-wheels
  extends: .container-runner-clariden-gh200
  image: $PERSIST_IMAGE_NAME
  variables:
    SLURM_TIMELIMT: '03:00:00'
  script:
    - |
      git clone https://github.com/fzyzcjy/torch_memory_saver.git ;\
      cd torch_memory_saver ;\
      git checkout b068987708fd0d744d231e3ccdd3b64eecbbeb82 ;\
      git submodule update --init --recursive ;\
      python3 setup.py bdist_wheel --dist-dir=${WHL_DIR} 2>&1 | tee ./build.log
  artifacts:
    paths:
      - ./*.whl

build final image:
  stage: build-image
  extends: .container-builder-cscs-gh200
  variables:
    DOCKERFILE: "ci/Dockerfile"
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/gh200_image:$CI_COMMIT_SHA
    DOCKER_BUILD_ARGS: '["BASEIMG=$CSCS_REGISTRY_PATH/base_image:$CI_COMMIT_SHA"]'

build test image:
  stage: test-image
  extends: .container-runner-clariden-gh200
  image: $PERSIST_IMAGE_NAME
  variables:
    SLURM_TIMELIMT: '03:00:00'
  script:
    - # TODO: Test image here
    - python3 -c "import torch; assert torch.cuda.is_available(); print(torch.__version__)"

publish wheel:
  stage: publish
  extends: .container-runner-lightweight-zen2
  rules:
    - if: $CI_COMMIT_REF == "main"
      when: on_success
  image: curl:latest
  script:
    - |
      find . -name *.whl | xargs -IF curl -L \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $GITHUB_TOKEN" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      -H "Content-Type: application/octet-stream" \
      "https://uploads.github.com/repos/swiss-ai/gh200-wheels/releases/RELEASE_ID/assets?name=F" \
      --data-binary "@F"
