FROM docker.io/nvidia/cuda:12.9.1-cudnn-devel-ubuntu24.04

ENV SRC_DIR=/workspace/src \
    WHL_DIR=/workspace/src/wheels

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y python3-pip git curl nvtop libnuma-dev cmake build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR ${SRC_DIR}

ENV DEBIAN_FRONTEND=noninteractive
ENV TORCH_CUDA_ARCH_LIST='9.0+PTX'
ENV VLLM_FA_CMAKE_GPU_ARCHES='90-real'
ENV CUDA_HOME=/usr/local/cuda

# ------- Build Dependencies -------
RUN pip3 install --no-cache-dir --root-user-action=ignore --break-system-packages \
    torch==2.8.0 torchvision==0.23.0 --index-url https://download.pytorch.org/whl/cu129

RUN pip install --no-cache-dir --root-user-action=ignore --break-system-packages \
    accelerate==1.10.1 \
    aiohttp==3.12.15 \
    aiohttp-cors==0.8.1 \
    anyio==4.11.0 \
    astor==0.8.1 \
    attrs==25.3.0 \
    blake3==1.0.6 \
    cachetools==5.5.2 \
    cbor2==5.7.0 \
    cffi==2.0.0 \
    cloudpickle==3.1.1 \
    codetiming==1.4.0 \
    compressed-tensors==0.11.0 \
    cupy-cuda12x==13.6.0 \
    datasets==4.0.0 \
    depyf==0.19.0 \
    dill==0.3.8 \
    diskcache==5.6.3 \
    distro==1.9.0 \
    dnspython==2.8.0 \
    einops==0.8.1 \
    email-validator==2.3.0 \
    fastapi==0.118.0 \
    fastapi-cli==0.0.13 \
    fastapi-cloud-cli==0.2.1 \
    fastrlock==0.8.3 \
    filelock==3.19.1 \
    frozendict==2.4.6 \
    frozenlist==1.7.0 \
    gguf==0.17.1 \
    google-api-core==2.25.1 \
    google-auth==2.40.3 \
    googleapis-common-protos==1.70.0 \
    h11==0.16.0 \
    hf_transfer==0.1.9 \
    httpcore==1.0.9 \
    httptools==0.6.4 \
    httpx==0.28.1 \
    hydra-core==1.3.2 \
    importlib_metadata==8.7.0 \
    interegular==0.3.3 \
    jiter==0.11.0 \
    jsonschema==4.25.1 \
    jsonschema-specifications==2025.9.1 \
    lark==1.2.2 \
    llguidance==1.2.0 \
    llvmlite==0.44.0 \
    lm-format-enforcer==0.11.3 \
    markdown-it-py==4.0.0 \
    mdurl==0.1.2 \
    mistral_common==1.8.5 \
    msgpack==1.1.1 \
    msgspec==0.19.0 \
    multidict==6.6.4 \
    multiprocess==0.70.16 \
    numba==0.61.2 \
    ninja==1.11.1.3 \
    omegaconf==2.3.0 \
    openai==1.109.1 \
    openai-harmony==0.0.4 \
    opencensus==0.11.4 \
    opencensus-context==0.1.3 \
    opencv-python-headless==4.12.0.88 \
    orjson==3.11.3 \
    outlines_core==0.2.11 \
    pandas==2.3.2 \
    partial-json-parser==0.2.1.1.post6 \
    peft==0.17.1 \
    prometheus-client==0.23.1 \
    prometheus-fastapi-instrumentator==7.1.0 \
    propcache==0.3.2 \
    proto-plus==1.26.1 \
    py-cpuinfo==9.0.0 \
    pyarrow==19.0.1 \
    pyasn1==0.6.1 \
    pyasn1-modules==0.4.2 \
    pybase64==1.4.2 \
    pycountry==24.6.1 \
    pycparser==2.23 \
    pycryptodomex==3.23.0 \
    pylatexenc==2.10 \
    python-dateutil==2.9.0.post0 \
    python-dotenv==1.1.1 \
    python-json-logger==3.3.0 \
    python-multipart==0.0.20 \
    pytz==2025.2 \
    pyzmq==27.1.0 \
    ray[default]==2.49.1 \
    referencing==0.36.2 \
    rich==14.1.0 \
    rich-toolkit==0.15.1 \
    rignore==0.6.4 \
    rpds-py==0.27.1 \
    rsa==4.9.1 \
    scikit-build-core==0.11.6 \
    scipy==1.16.2 \
    sentencepiece==0.2.1 \
    setproctitle==1.3.7 \
    shellingham==1.5.4 \
    six==1.17.0 \
    sniffio==1.3.1 \
    soundfile==0.13.1 \
    soxr==1.0.0 \
    starlette==0.48.0 \
    tensordict==0.10.0 \
    tiktoken==0.11.0 \
    tokenizers==0.22.1 \
    transformers==4.56.2 \
    typer==0.19.2 \
    tzdata==2025.2 \
    uvicorn==0.37.0 \
    uvloop==0.21.0 \
    watchfiles==1.1.0 \
    websockets==15.0.1 \
    xgrammar==0.1.25 \
    xxhash==3.5.0 \
    yarl==1.20.1 \
    zipp==3.23.0
# ----------------------------
